### ISSUE TITLE
merge_mod_par issue

### ISSUE THREAD

**Issue by qwertyuiopxu1** [DanielT/a2lfile#20]
Hi,
when i use a2ltool to merge a2l files, but the mod_par part has issues because currently the SYSTEM_CONSTANT is not considered. only consider the MEMORY_LAYOUT and MEMORY_SEGMENT elements. but the SYSTEM_CONSTANT elements are alao need to merge.

**Comment by DanielT** [comment]
Interesting. I never considered this, since I have no files that use system constants.
Presumably you us the defined constants in conversion formulas?

**Comment by qwertyuiopxu1** [comment]
Hi, 
thanks for your comments. but i want to know how to use this update for the a2ltool?

**Comment by DanielT** [comment]
At the moment you would have to modify the cargo.toml of a2ltool to use the latest git version of a2lfile and then build it yourself.
I intend to make some other changes and then I will release new versions of both, but that will take a few days
