### ISSUE TITLE
a2l merge group or function issue

### ISSUE THREAD

**Issue by qwertyuiopxu1** [DanielT/a2lfile#22]
Hi,
this is a very useful and fast tool for the a2l merge.
but when merge group and funtion the REF_MEASURMENT varaibels will be added the .MERGE. 
this is wrong process for group and function merge operation. but for the measurements and characteristics.

**Comment by qwertyuiopxu1** [comment]
![image](https://github.com/DanielT/a2lfile/assets/102847561/a45ad2fb-253e-4774-b6a7-a7ed1b2f1c66)

**Comment by qwertyuiopxu1** [comment]
![image](https://github.com/DanielT/a2lfile/assets/102847561/d7c437fc-fb2d-4422-9c02-21e26f085081)
the correct opration result is the group should keep the raw value.

**Comment by qwertyuiopxu1** [comment]
one more thing , if you fix the issue, how can i use the fixed version with the a2ltool?

**Comment by DanielT** [comment]
I don't understand why you think this is a problem. Can you explain in more detail?

**Comment by DanielT** [comment]
At the moment I am not convinced that there is a problem here.
You are welcome to give additional details to convince me otherwise.

I will close this issue next week if I receive no additional information.
