### ISSUE TITLE
DISPLAY_IDENTIFIER that starts with a number causes a tokenization exception

### ISSUE THREAD

**Issue by Eltom777** [DanielT/a2lfile#23]
I have encountered an a2l which contains DISPLAY_IDENTIFIER names that start with a number. This causes an "**TokenizerError { tokenizer_error: MissingWhitespace**" error to be thrown when the a2lfile loads the a2l.

The screenshot below contains an example:

![Screenshot from 2023-11-09 17-20-34](https://github.com/DanielT/a2lfile/assets/9936660/b5b66504-89cf-44b6-8d1a-1992eb7ee777)

I do not know if a DISPLAY_IDENTIFIER name that starts with a number is valid in the a2l format. If it isn't, than this issue could be ignored or a feature could be added to the parser to detect this illegal name type. Then, a more appropriate error could be raised.

**Comment by DanielT** [comment]
Identifiers in a2l files are not allowed to start with digits. In fact only numeric literals can contain a digit in the first position.

Accordingly, the tokenizer sees a numeric literal when it encounters the '1' of "1ms", then it considers 'm' to be the beginning of the next token and complains about missing whitespace between the two.

**Comment by DanielT** [comment]
I should add that various tools have different levels of "standard compliance". It's possible that your file was created and processed without complaint by some other application. In that case it may be worth adding some kind of compatibility workaround.

**Comment by Eltom777** [comment]
Thank you @DanielT for the quick response. I would also like to add that this tool is amazing. It is much more robust than the other a2l parsers available on Github. Great work !

**Comment by DanielT** [comment]
You're welcome.
I thought about this some more and decided that a code change is needed after all: There should be better error messages in this case. I'm changing this case to produce a `ParserError::InvalidIdentifier` instead of the confusing MissingWhitespace error.
