### ISSUE TITLE
Extract Record Layout field from Characteristics variables

### ISSUE THREAD

**Issue by Eltom777** [DanielT/a2lfile#28]
Is it possible to extract the Record_Layout field from a Characteristic variable using a2lFile's parser ?

Ex: 
Assuming I have the following Characteristic variable called **CoF_swtFlt0_C**, is it possible to extract the record layout's value *SCALAR_UBYTE*  ?

![image](https://github.com/DanielT/a2lfile/assets/9936660/40c09ed9-6ebe-444c-b7eb-8cb27a4573bb)

**Comment by DanielT** [comment]
Yes, but the field name is "deposit" according to the specification.
Assuming you already have a reference to your characteristic called `c`, then `c.deposit` gives you the value "Scalar_UBYTE"

**Comment by Eltom777** [comment]
Thank you @DanielT. This is the specification a2lFile is based on: https://www.asam.net/standards/detail/mcd-2-mc/wiki/ ?

**Comment by DanielT** [comment]
yes, a2l files are specified by ASAM. Unfortunately they don't make the specification public.
