### ISSUE TITLE
Please add a CHAGELOG and use SemVer

### ISSUE THREAD

**Issue by therealevahill** [DanielT/a2lfile#30]
At first thanks for your great crate and our effort.

It would be nice if you could add CHANGELOG to your repo. So it is really easy for all users of your crate to see the the differences of the versions. If I could suggest a changelog format, I would use https://keepachangelog.com/en/1.0.0/

It would be nice too, if you could use / switch semantic versioning https://semver.org/
Rust uses SemVer as default for specifing dependencies https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by DanielT** [comment]
Hi, I'm glad you find the crate useful.

Regarding the changelog: Since version 1.0 a2lfile has been essentially done. Since then there have only been occasional bugfixes and a small number of minor tweaks. In my opinion having a mostly empty and rarely changing CHANGELOG would not be positive.

I'm familiar with SemVer, and as far as I can tell I've followed it. Did you have a specific problem that caused you to request following SemVer?

**Comment by therealevahill** [comment]
sorry to say, but yes, I had some trouble.
in cargo.toml a2lfile = "1.3.2" was specified.
when i compiled it I got different errors.
One of them was 
expected `&mut Vec<A2lError>` but found `&mut Vec<String>` 
at https://github.com/DanielT/a2lfile/blob/6e1990fa35e40818f9664d953cff7efd10b017df/src/lib.rs#L132
Another error was harder to find, because in the background a new version of a2lmacros was used.

**Comment by DanielT** [comment]
I see. That's unfortunate, and not really fixable at this point.
You'll have to force the use of the older version using Cargo.lock

**Comment by therealevahill** [comment]
Yes I have done so.
To avoid such stuff, you could probably use https://crates.io/crates/cargo-semver-checks
and add it to your CI pipeline?

**Comment by DanielT** [comment]
If you want to send a pull request, I'd be happy to take it.

I have no intention of implementing that myself: The change that caused problems for you was actually the last item on my personal todo list. Unless that changes, a2lfile is in maintainance mode, where I'll only fix any bugs that I become aware of.
Basically, I don't see any reason for the API to change any more.
